# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI and master/Release branch
branches:
  only:
    - dev
    - master

skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
test: off

install:
  # Install Microsoft Windows SDK for Windows 10 and .NET Framework 4.7 10.1.17763.1
  #- cinst windows-sdk-10.1
  - ps: Start-FileDownload 'https://go.microsoft.com/fwlink/p/?LinkID=2033908'
  - ps: Start-Process .\winsdksetup.exe "/features /norestart /quiet" -NoNewWindow -Wait
  # Install dotnet core 3.0 latest (alpha!!), as this is not provided on AppVeyor yet
  #- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe'
  #- ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
  - ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/3.0.100-preview4-010332/dotnet-sdk-3.0.100-preview4-010332-win-x64.exe'
  - ps: Start-Process .\dotnet-sdk-3.0.100-preview4-010332-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
  - ps: iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/onovotny/UpdateVsOnAgent/master/Fix-VisualStudioPreviewNuGetSdk.ps1'))

pull_requests:
  do_not_increment_build_number: false

build_script:
  - ps: cd src
  - ps: .\build.ps1 -Target appveyor
  - ps: cd..

artifacts:
  - path: \src\Publish\*.*

nuget:
  disable_publish_on_pr: true
